services:
  vinnie:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./data:/data
      - ./frontend:/frontend:ro
      - whisper_cache:/home/appuser/.cache/huggingface
    env_file: .env
    environment:
      - OS_TYPE=linux
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  whisper_cache:
